name: Frontend · Deploy to CapRover
on:
  push:
    branches: [ "main" ]
    paths:
      - "**"
env:
  CAPROVER_APPNAME: palco-app-frontend
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1
        with:
          server: ${{ secrets.CAPROVER_URL }}
          app: ${{ env.CAPROVER_APPNAME }}
          token: ${{ secrets.CAPROVER_TOKEN_PALCO_FRONTEND }}
          branch: main
          # Si tu código está en subcarpeta, agrega: path: "frontend"
